# 自动生成：Material You Fuzzel 主题
[main]
font=JetBrainsMono Nerd Font:size=12
prompt="❯ "
terminal=alacritty
width=30
horizontal-pad=20
vertical-pad=10
inner-pad=5

[colors]
# 修正后的变量名：hex_stripped
background=13140dff
text=e4e3d6ff
match=c0ce7dff
selection=414b08ff
selection-text=dcea97ff
selection-match=c0ce7dff
border=919283ff

[border]
width=2
radius=10
