# 自动生成：Material You Fuzzel 主题
[main]
font=JetBrainsMono Nerd Font:size=12
prompt="❯ "
terminal=alacritty
width=30
horizontal-pad=20
vertical-pad=10
inner-pad=5

[colors]
# 修正后的变量名：hex_stripped
background=1a110fff
text=f1dfdbff
match=ffb4a3ff
selection=723425ff
selection-text=ffdad2ff
selection-match=ffb4a3ff
border=a08c88ff

[border]
width=2
radius=10
