# 自动生成：Material You Fuzzel 主题
[main]
font=JetBrainsMono Nerd Font:size=12
prompt="❯ "
terminal=alacritty
width=30
horizontal-pad=20
vertical-pad=10
inner-pad=5

[colors]
# 修正后的变量名：hex_stripped
background=0e1415ff
text=dee4e4ff
match=81d4dcff
selection=004f55ff
selection-text=9df0f9ff
selection-match=81d4dcff
border=899393ff

[border]
width=2
radius=10
