#preload = /home/cao/Pictures/wallpapers/city_photography.jpg
#preload = '/home/cao/Pictures/wallpapers/Boonie Bears: To the Rescue.jpg'
preload = /home/cao/Pictures/wallpapers/马达加斯加的黑白环尾狐猴.jpg
wallpaper = , /home/cao/Pictures/wallpapers/马达加斯加的黑白环尾狐猴.jpg
