[colors]
background = #e41a1b26
background-alt = #24283b
foreground = #c0caf5
primary = #7aa2f7
secondary = #bb9af7
tertiary = #f9e2af
green = #a1dc9c
alert = #f7768e
disabled = #414868

[bar/main]
width = 100%
height = 26pt
radius = 0
bottom = true
background = ${colors.background}
foreground = ${colors.foreground}
line-size = 3pt
padding-left = 2
padding-right = 2
module-margin = 1

font-0 = "Inter Medium:size=12;3"
font-1 = "JetBrainsMono Nerd Font Propo:size=14;4"

modules-left = launcher separator workspaces layout xwindow
modules-center = media 
modules-right = tray separator netspeed-wifi netspeed-eth pulseaudio memory cpu date
cursor-click = pointer
enable-ipc = true
wm-restack = i3

[module/media]
type = custom/script
exec = python3 ~/.config/polybar/scripts/media.py
tail = true
label = %output%

[module/workspaces]
type = custom/script
exec = ~/.config/polybar/scripts/workspaces.py
tail = true
format = <label>
label = %output% 
label-font = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:38:...%
label-foreground = ${colors.secondary}
background = ${colors.background-alt}


; [module/xworkspaces]
; type = internal/xworkspaces
; label-active = 󰮯
; label-active-foreground = ${colors.tertiary}
; label-active-padding = 2
; label-occupied = 󰊠
; label-occupied-foreground = ${colors.foreground}
; label-occupied-padding = 2

; [module/xwindow]
; type = internal/xwindow
; label = %title:0:38:...%
; label-foreground = ${colors.secondary}

[module/layout]
type = custom/script
exec = python3 ~/.config/polybar/scripts/i3wm.py
tail = true
label = %output%
label-padding = 1

[module/launcher]
type = custom/text
label = 󰣇
content-font = 1
content-padding = 1
content-foreground = ${colors.primary}
click-left = rofi -show drun

[module/separator]
type = custom/text
label = |
content-foreground = ${colors.disabled}
content-padding = 1

[module/tray]
type = internal/tray
tray-spacing = 5px
tray-size = 55%

[module/pulseaudio]
type = internal/pulseaudio
format-volume-prefix = "%{F#bb9af7}  "
format-volume = <label-volume>
label-volume = %percentage%%
label-volume-foreground = ${colors.foreground}
format-muted-prefix = "%{F#f7768e}󰝟  "
format-muted = <label-muted>
label-muted = MUTE
label-muted-foreground = ${colors.alert}
click-right = pavucontrol

[module/memory]
type = internal/memory
interval = 2
format-prefix = "%{F#f9e2af}   "
label = %percentage_used:2%%
label-foreground = ${colors.foreground}
click-left = btop

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "%{F#7aa2f7}  "
label = %percentage:2%%
label-foreground = ${colors.foreground}
click-left = btop

[module/date]
type = internal/date
interval = 1
format-prefix = "%{F#ffbcff}  "
date = %I:%M %p
date-alt = %B %d, %Y %I:%M %p
label = %date%
label-foreground = ${colors.foreground}

[module/left-bracket]
type = custom/text
label = [
content-foreground = ${colors.primary}

[module/right-bracket]
type = custom/text
label = ]
content-foreground = ${colors.primary}
[module/netspeed]
type = internal/network
interface-type = wired
interval = 2
accumulate-stats = true
unknown-as-up = true
speed-unit = B/s
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-connected = %{F#a1dc9c}%{F#c0caf5}%netspeed:9%
label-disconnected = %{F#414868}
label-disconnected-foreground = ${colors.disabled}

[module/netspeed-wifi]
type = internal/network
interface-type = wireless
interval = 2
accumulate-stats = true
speed-unit = B/s
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-connected = %{F#a1dc9c}%{F#c0caf5}%netspeed:9%
label-disconnected =
label-disconnected-foreground = ${colors.disabled}

[module/netspeed-eth]
type = internal/network
interface-type = wired
interval = 2.0
unknown-as-up = true
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-connected = %{F#a1dc9c}%{F#c0caf5}%netspeed:9%
label-disconnected = ""
